In [4]:
import numpy as np

a = np.meshgrid([1], [2], [3])

a[0].shape

(1, 1, 1)

In [8]:
b = np.array(a)

c = (b.T).reshape(-1, 3)

c.shape

(1, 3)

In [10]:
R = np.linspace(100, 255, 3, dtype=np.uint8)
G = np.roll(R, 1)
B = np.roll(R, 2)

R, G, B

(array([100, 177, 255], dtype=uint8),
 array([255, 100, 177], dtype=uint8),
 array([177, 255, 100], dtype=uint8))

In [15]:
colors = np.array(np.meshgrid(R,G,B))

colors = colors.T.reshape(-1, 3)
print(colors.shape)
print(colors)

(27, 3)
[[100 255 177]
 [100 100 177]
 [100 177 177]
 [177 255 177]
 [177 100 177]
 [177 177 177]
 [255 255 177]
 [255 100 177]
 [255 177 177]
 [100 255 255]
 [100 100 255]
 [100 177 255]
 [177 255 255]
 [177 100 255]
 [177 177 255]
 [255 255 255]
 [255 100 255]
 [255 177 255]
 [100 255 100]
 [100 100 100]
 [100 177 100]
 [177 255 100]
 [177 100 100]
 [177 177 100]
 [255 255 100]
 [255 100 100]
 [255 177 100]]


In [16]:
a = np.arange(100, dtype=np.uint8).reshape(10,10)

a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]], dtype=uint8)

In [18]:
a[4:6, 4:8] = 125

a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43, 125, 125, 125, 125,  48,  49],
       [ 50,  51,  52,  53, 125, 125, 125, 125,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]], dtype=uint8)

In [19]:
indices = np.where(a >= 100)
indices

(array([4, 4, 4, 4, 5, 5, 5, 5]), array([4, 5, 6, 7, 4, 5, 6, 7]))

In [24]:
np.array(indices).T

array([[4, 4],
       [4, 5],
       [4, 6],
       [4, 7],
       [5, 4],
       [5, 5],
       [5, 6],
       [5, 7]])

In [21]:
a[indices]

array([125, 125, 125, 125, 125, 125, 125, 125], dtype=uint8)

In [22]:
yy, xx = indices

left, right = xx.min(), xx.max()
top, bottom = yy.min(), yy.max()

(left, top), (right, bottom)

((np.int64(4), np.int64(4)), (np.int64(7), np.int64(5)))